"""Session store interface -- wraps LangGraph checkpointer for DI."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SessionStore(Protocol):
    def get_checkpointer(self) -> Any:  # BaseCheckpointSaver
        ...

    async def list_sessions(
        self, user_id: str, *, include_all: bool = False
    ) -> list[dict]: ...
    async def list_sessions_by_prefixes(
        self, prefixes: tuple[str, ...]
    ) -> list[dict]: ...
    async def delete_session(self, thread_id: str) -> bool: ...
    async def get_session_owner(self, thread_id: str) -> str | None: ...
    async def get_session_metadata(self, thread_id: str) -> dict | None: ...
    async def get_messages(self, thread_id: str) -> list[dict]: ...
